### ISSUE TITLE
Refactor tab colors

### ISSUE THREAD

**Issue by gfellerph** [swisspost/common-web-frontend#100]
Tab colors rely on the `.text-auto` class which is deprecated. Refactor tab colors so the class can be removed from `utilities.scss`.

**Comment by oliverschuerch** [comment]
@gfellerph Is there a new Class we can switch to, so we can get rid of `text-auto`?

**Comment by oliverschuerch** [comment]
Set :hover/:focus-visible, etc. for light backgrounds by default with full-tone-color (#fff). Set the opacity of this color to 0.2 for dark backgrounds. Remove `has-background` mixin.
