### ISSUE TITLE
fix(background): secondary color variable not available anymore

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/common-web-frontend#256]
The color variable `$secondary` has been deleted in the commit with the hash 56be7d6 (marked as BREAKING_CHANGE).
This means that the following classes are no longer available in the entire CWF:
- `bg-secondary`
- `btn-secondary` (class is available, but does not provide a background color anymore)
- `text-secondary`
- `border-secondary`

However, these classes are still used in the package web-demo, but without the desired effect.
@gfellerph we need to discuss, how we want to deal with it.

**Comment by gfellerph** [comment]
@oliverschuerch replaced classes that still were in the demo. This color should not be used anymore (we have the grayscales as replacement). The secondary button intentionally has a transparent background to make it work on colorful backgrounds.
