### ISSUE TITLE
fix(form-checkbox/form-radio): invalid checkbox/radio on dark background

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/common-web-frontend#261]
The checkbox/radio background is white, unlike the background of a valid checkbox/radio.
This leads to a different appearance of a valid and an invalid checkbox/radio on colored backgrounds.

The background of an unchecked, invalid checkbox/radio should be transparent.

![image](https://user-images.githubusercontent.com/9716662/182873358-1e7bfdd0-c783-4ed5-9084-376bf44585ab.png)

![image](https://user-images.githubusercontent.com/9716662/183041953-28883dba-efcd-4374-ae0b-0b0a6fa0081b.png)

![image](https://user-images.githubusercontent.com/9716662/182873428-13eb1688-d82c-4384-9dcc-de56928af87f.png)

**Comment by gfellerph** [comment]
Discuss with @rouvenpost and @wueestd.

**Comment by oliverschuerch** [comment]
Discussion started internally!

**Comment by oliverschuerch** [comment]
@rouvenpost reported: "seems correct to me..."

**Comment by gfellerph** [comment]
This ticket can be closed as won't fix. We can discuss a possible redesign for future versions.
