### ISSUE TITLE
fix(form-multiple-select safari): size-attribute not working

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/common-web-frontend#263]
It seems that Safari on Mac OS does not correctly take into account the size-attribute.
Therefore, no scrollbar appears for the multiple-select element, as is the case with all the other desktop browsers.

**Chrome screenshot **
![image](https://user-images.githubusercontent.com/9716662/183040317-b388bb18-1141-4fec-b7a5-6ec2f9a4194d.png)

**Safari screenshot **
![image](https://user-images.githubusercontent.com/9716662/183040464-9c1d2abd-fc5a-40f8-badf-a3c709ba61b2.png)

**Comment by oliverschuerch** [comment]
Try adding the `multiple` attribute to the select element. This might fix the problem immediately.

**Comment by gfellerph** [comment]
This seems to be a known issue with webkit browsers. It works however if there are more items and the size is bigger than 4: http://jsfiddle.net/ddWr2/.
