### ISSUE TITLE
fix(alert & notifications chrome): no focus-visible indicator

### ISSUE THREAD

**Issue by LarissaMS** [swisspost/common-web-frontend#293]
![image](https://user-images.githubusercontent.com/81462538/183901855-3886aa9b-b233-4b59-9925-f8cb999ad361.png)
![image](https://user-images.githubusercontent.com/81462538/183901947-fa80d7e4-fc38-4b0c-9a9b-36f1426fc604.png)
![image](https://user-images.githubusercontent.com/81462538/183900823-d37c73e1-c04f-434f-9b57-53d4b552939a.png)

- [ ] Chrome does not display a focus-visible indicator on the "Information", "Special Icons (Black)" and "Example for dismissible alert" notification when tabbing through the page.

**Comment by gfellerph** [comment]
- [ ] All alerts should have the same style, a black background and standard text in HCM (this likely improves the focus situation)
