### ISSUE TITLE
fix(form select firefox): no focus-visible indicator

### ISSUE THREAD

**Issue by LarissaMS** [swisspost/common-web-frontend#296]
- [x] Firefox does not display a focus-visible indicator on the form-select when tabbing through the page.
- [ ] ~~Color of "Custom select" hardly visible.~~

![image](https://user-images.githubusercontent.com/81462538/183922087-c6991553-3961-4151-9ccf-3aea7c6dbd3b.png)

**Comment by gfellerph** [comment]
Color of "Custom select" will be fixed in another ticket.
