### ISSUE TITLE
fix(sizing chrome/firefox): visualizations are not shown

### ISSUE THREAD

**Issue by LarissaMS** [swisspost/common-web-frontend#343]
Visualizations for margin, padding and content are not shown properly:
![image](https://user-images.githubusercontent.com/81462538/184672231-57f2f1ce-41db-4ece-9fb7-102b23b8ee07.png)
![image](https://user-images.githubusercontent.com/81462538/184672273-f77092f9-625f-4339-ad94-a7f0bb0657a8.png)
![image](https://user-images.githubusercontent.com/81462538/184672318-8253cd70-bf05-4203-a1ab-c22b1aa94085.png)

**Comment by gfellerph** [comment]
No HCM support necessary here.
